apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
      - name: podinfod
        env:
        - name: PODINFO_UI_COLOR
          value: '#1d2d35'
        - name: PODINFO_UI_MESSAGE
          value: 'greetings from Avisi Cloud'
